import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairsEffect from "@/components/StairsEffect";
import PreloaderWrapper from "@/components/PreLoaderWrapper";
import { Toaster } from "react-hot-toast";

const jetbrainsmMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetbrainsmMono.variable}  antialiased`}>
        <PreloaderWrapper>
          <Toaster position="top-right" />
            <Header />
            <StairsEffect />
            <PageTransition>{children}</PageTransition>
          
        </PreloaderWrapper>
      </body>
    </html>
  );
}
